version: '3.7'

services:
  cache:  
    image: "redis:alpine"
    container_name: cache
    command: redis-server --requirepass securePass1092
    ports:
      - 6379:6379

  app:
    build: .
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
      placement:
        constraints: [node.role == manager]
    environment:
      - IN_MEMORY_CACHE_URL=cache
      - IN_MEMORY_CACHE_AUTH_URL=securePass1092
      - IN_MEMORY_CACHE_EXPIRY=60
      - IN_MEMORY_CACHE_PORT=6379
      - MIDDLEWARE_AUTH=Basic ZWxhc3RpYzpwbGR1bW15ZGV2MUAyMQ==
      - PORT=1328
    ports:
      - 1328:1328
    depends_on:
      - cache

  nginx:
    image: nginx:alpine
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      update_config:
        parallelism: 1
      placement:
        constraints: [node.role == manager]
    ports:
      - 80:80
      - 443:443
    secrets:
      - source: nginx-config
        target: /etc/nginx/conf.d/default.conf
    depends_on:
      - app

secrets:
  nginx-config:
    file: deployment/nginx/default.conf